### ISSUE TITLE
Origin, Destination, Line, ETA, Mapbox, and Website

### ISSUE THREAD

**Issue by NatalieGates** [grumpypixel/msfs2020-gopilot#3]
1. Is it possible to put this map on my personal website (github pages)? If so, how would I integrate it? (for example, I would like a full page on my personal website that I could go to that shows my live flight. When not connected, it's just an empty page that says "next flight on <insert date and time>")
2. Is it possible to add a line showing the path from the origin airport to the destination airport?
3. Can there be data somewhere on the screen that shows the ETA?
4. If I add my mapbox token, what can I do with that and how would I do it? Could you provide an example(s)?

thanks for making this. I like it.

**Comment by grumpypixel** [comment]
Thank you very much for your message.

1. I actually thought about something similar but didn't proceed with it due to the lack of time. But I totally agree, it would be nice to integrate a map on one's personal website and show the live flight. I will definitely add this to my reasearch list since I'm also very interested in this.

2. Yes, I think it would be possible to add a line from the origin airport to the destination airport. (I already have "display flight path" on my list...)

3. It's also possible to add the "enroute time estimate" (GPS ETE) and "enroute time actual" (GPS ETA). Maybe there is also an option to add an "Estimated time of Arrival". Great idea!

4. If you add your own Mapbox token, you don't have to share the built-in token with other users. Which means that you are less likely to run into a situation where your Mapbox usage will be limited. (I have no clue how many people are using this program with Mapbox, though). 

The built-in token is using the free tier, so the requests per day are limited (https://www.mapbox.com/pricing/).

Example:
 ```
http://localhost:8888/?mapbox_token=Y0UrSuP3Rs3cR3Tm4pB0Xt0k3n
```
---

I will add your requests to my todo list. Point 2) and 3) can be done pretty quickly. Regarding 1) I cannot promise anything at the moment, since it will take some time for me to evaluate this point. (Sorry about that!)

Nonetheless, thank you for using GoPilot, I really appreciate it!

If you have more ideas for features, improvements or whatsoever, please let me know.

Best,
Sascha

**Comment by NatalieGates** [comment]
ty
